[application]

# App name
name = "hot_dog"

# `build` & `serve` output path
out_dir = "dist"

# The static resource path
asset_dir = "public"

[bundle]
identifier = "com.dioxuslabs"
publisher = "DioxusLabs"
icon = ["assets/icon.png"]

[web.app]
# HTML title tag content
title = "hot_dog"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
